###服务端口号
server:
  port: 8100
###eureka 基本信息配置
spring:
 application:
  name: eureka-server

eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#     defaultZone: http://${eureka.instance.hostname}:8101/eureka/
###因为自己是为注册中心，不需要自己注册自己（如果高可用相互注册）
    register-with-eureka: false
###因为自己是为注册中心，不需要检索服务（如果高可用相互注册）
    fetch-registry: false
##开发环境关闭自我保护机制
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
##   eviction-interval-timer-in-ms: 2000

